numero1 = int(input("Dígame un número: "))
numero2 = int(input(f"Dígame un número mayor que {numero1}: "))
print(f"La diferencia entre ellos es {numero2 - numero1}.")
print(f"La suma entre ellos es {numero2 + numero1}.")
print(f"La division de ellos es {numero2 / numero1}.")
